/*
 * This file is generated by jOOQ.
 */
package jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITbAccomodation extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.tb_accomodation.id</code>.
     */
    public ITbAccomodation setId(Long value);

    /**
     * Getter for <code>public.tb_accomodation.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.tb_accomodation.serialNumber</code>.
     */
    public ITbAccomodation setSerialnumber(String value);

    /**
     * Getter for <code>public.tb_accomodation.serialNumber</code>.
     */
    public String getSerialnumber();

    /**
     * Setter for <code>public.tb_accomodation.name</code>.
     */
    public ITbAccomodation setName(String value);

    /**
     * Getter for <code>public.tb_accomodation.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.tb_accomodation.abbrevation</code>.
     */
    public ITbAccomodation setAbbrevation(String value);

    /**
     * Getter for <code>public.tb_accomodation.abbrevation</code>.
     */
    public String getAbbrevation();

    /**
     * Setter for <code>public.tb_accomodation.units</code>.
     */
    public ITbAccomodation setUnits(String value);

    /**
     * Getter for <code>public.tb_accomodation.units</code>.
     */
    public String getUnits();

    /**
     * Setter for <code>public.tb_accomodation.dormBedsPerRoom</code>.
     */
    public ITbAccomodation setDormbedsperroom(Integer value);

    /**
     * Getter for <code>public.tb_accomodation.dormBedsPerRoom</code>.
     */
    public Integer getDormbedsperroom();

    /**
     * Setter for <code>public.tb_accomodation.totalAccomodation</code>.
     */
    public ITbAccomodation setTotalaccomodation(Integer value);

    /**
     * Getter for <code>public.tb_accomodation.totalAccomodation</code>.
     */
    public Integer getTotalaccomodation();

    /**
     * Setter for <code>public.tb_accomodation.createdOn</code>.
     */
    public ITbAccomodation setCreatedon(OffsetDateTime value);

    /**
     * Getter for <code>public.tb_accomodation.createdOn</code>.
     */
    public OffsetDateTime getCreatedon();

    /**
     * Setter for <code>public.tb_accomodation.createdBy</code>.
     */
    public ITbAccomodation setCreatedby(String value);

    /**
     * Getter for <code>public.tb_accomodation.createdBy</code>.
     */
    public String getCreatedby();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITbAccomodation
     */
    public void from(ITbAccomodation from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITbAccomodation
     */
    public <E extends ITbAccomodation> E into(E into);

    @Override
    public default ITbAccomodation fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getLong("id"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.Long",e);
        }
        try {
            setSerialnumber(json.getString("serialNumber"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("serialNumber","java.lang.String",e);
        }
        try {
            setName(json.getString("name"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("name","java.lang.String",e);
        }
        try {
            setAbbrevation(json.getString("abbrevation"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("abbrevation","java.lang.String",e);
        }
        try {
            setUnits(json.getString("units"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("units","java.lang.String",e);
        }
        try {
            setDormbedsperroom(json.getInteger("dormBedsPerRoom"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("dormBedsPerRoom","java.lang.Integer",e);
        }
        try {
            setTotalaccomodation(json.getInteger("totalAccomodation"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("totalAccomodation","java.lang.Integer",e);
        }
        try {
            // Omitting unrecognized type java.time.OffsetDateTime for column createdOn!
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("createdOn","java.time.OffsetDateTime",e);
        }
        try {
            setCreatedby(json.getString("createdBy"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("createdBy","java.lang.String",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("serialNumber",getSerialnumber());
        json.put("name",getName());
        json.put("abbrevation",getAbbrevation());
        json.put("units",getUnits());
        json.put("dormBedsPerRoom",getDormbedsperroom());
        json.put("totalAccomodation",getTotalaccomodation());
        // Omitting unrecognized type java.time.OffsetDateTime for column createdOn!
        json.put("createdBy",getCreatedby());
        return json;
    }

}
