/*
 * This file is generated by jOOQ.
 */
package jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITbPropertyProfile extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.tb_property_profile.id</code>.
     */
    public ITbPropertyProfile setId(Long value);

    /**
     * Getter for <code>public.tb_property_profile.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.tb_property_profile.serialNumber</code>.
     */
    public ITbPropertyProfile setSerialnumber(String value);

    /**
     * Getter for <code>public.tb_property_profile.serialNumber</code>.
     */
    public String getSerialnumber();

    /**
     * Setter for <code>public.tb_property_profile.type</code>.
     */
    public ITbPropertyProfile setType(String value);

    /**
     * Getter for <code>public.tb_property_profile.type</code>.
     */
    public String getType();

    /**
     * Setter for <code>public.tb_property_profile.description</code>.
     */
    public ITbPropertyProfile setDescription(String value);

    /**
     * Getter for <code>public.tb_property_profile.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>public.tb_property_profile.image</code>.
     */
    public ITbPropertyProfile setImage(String value);

    /**
     * Getter for <code>public.tb_property_profile.image</code>.
     */
    public String getImage();

    /**
     * Setter for <code>public.tb_property_profile.name</code>.
     */
    public ITbPropertyProfile setName(String value);

    /**
     * Getter for <code>public.tb_property_profile.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.tb_property_profile.phone</code>.
     */
    public ITbPropertyProfile setPhone(String value);

    /**
     * Getter for <code>public.tb_property_profile.phone</code>.
     */
    public String getPhone();

    /**
     * Setter for <code>public.tb_property_profile.email</code>.
     */
    public ITbPropertyProfile setEmail(String value);

    /**
     * Getter for <code>public.tb_property_profile.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>public.tb_property_profile.website</code>.
     */
    public ITbPropertyProfile setWebsite(String value);

    /**
     * Getter for <code>public.tb_property_profile.website</code>.
     */
    public String getWebsite();

    /**
     * Setter for <code>public.tb_property_profile.ownerFirstName</code>.
     */
    public ITbPropertyProfile setOwnerfirstname(String value);

    /**
     * Getter for <code>public.tb_property_profile.ownerFirstName</code>.
     */
    public String getOwnerfirstname();

    /**
     * Setter for <code>public.tb_property_profile.ownerLastName</code>.
     */
    public ITbPropertyProfile setOwnerlastname(String value);

    /**
     * Getter for <code>public.tb_property_profile.ownerLastName</code>.
     */
    public String getOwnerlastname();

    /**
     * Setter for <code>public.tb_property_profile.country</code>.
     */
    public ITbPropertyProfile setCountry(String value);

    /**
     * Getter for <code>public.tb_property_profile.country</code>.
     */
    public String getCountry();

    /**
     * Setter for <code>public.tb_property_profile.address1</code>.
     */
    public ITbPropertyProfile setAddress1(String value);

    /**
     * Getter for <code>public.tb_property_profile.address1</code>.
     */
    public String getAddress1();

    /**
     * Setter for <code>public.tb_property_profile.address2</code>.
     */
    public ITbPropertyProfile setAddress2(String value);

    /**
     * Getter for <code>public.tb_property_profile.address2</code>.
     */
    public String getAddress2();

    /**
     * Setter for <code>public.tb_property_profile.city</code>.
     */
    public ITbPropertyProfile setCity(String value);

    /**
     * Getter for <code>public.tb_property_profile.city</code>.
     */
    public String getCity();

    /**
     * Setter for <code>public.tb_property_profile.postalCode</code>.
     */
    public ITbPropertyProfile setPostalcode(String value);

    /**
     * Getter for <code>public.tb_property_profile.postalCode</code>.
     */
    public String getPostalcode();

    /**
     * Setter for <code>public.tb_property_profile.locationCoordinate</code>.
     */
    public ITbPropertyProfile setLocationcoordinate(String value);

    /**
     * Getter for <code>public.tb_property_profile.locationCoordinate</code>.
     */
    public String getLocationcoordinate();

    /**
     * Setter for <code>public.tb_property_profile.createdOn</code>.
     */
    public ITbPropertyProfile setCreatedon(LocalDateTime value);

    /**
     * Getter for <code>public.tb_property_profile.createdOn</code>.
     */
    public LocalDateTime getCreatedon();

    /**
     * Setter for <code>public.tb_property_profile.createdBy</code>.
     */
    public ITbPropertyProfile setCreatedby(String value);

    /**
     * Getter for <code>public.tb_property_profile.createdBy</code>.
     */
    public String getCreatedby();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITbPropertyProfile
     */
    public void from(ITbPropertyProfile from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITbPropertyProfile
     */
    public <E extends ITbPropertyProfile> E into(E into);

    @Override
    public default ITbPropertyProfile fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getLong("id"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.Long",e);
        }
        try {
            setSerialnumber(json.getString("serialNumber"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("serialNumber","java.lang.String",e);
        }
        try {
            setType(json.getString("type"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("type","java.lang.String",e);
        }
        try {
            setDescription(json.getString("description"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("description","java.lang.String",e);
        }
        try {
            setImage(json.getString("image"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("image","java.lang.String",e);
        }
        try {
            setName(json.getString("name"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("name","java.lang.String",e);
        }
        try {
            setPhone(json.getString("phone"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("phone","java.lang.String",e);
        }
        try {
            setEmail(json.getString("email"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("email","java.lang.String",e);
        }
        try {
            setWebsite(json.getString("website"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("website","java.lang.String",e);
        }
        try {
            setOwnerfirstname(json.getString("ownerFirstName"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("ownerFirstName","java.lang.String",e);
        }
        try {
            setOwnerlastname(json.getString("ownerLastName"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("ownerLastName","java.lang.String",e);
        }
        try {
            setCountry(json.getString("country"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("country","java.lang.String",e);
        }
        try {
            setAddress1(json.getString("address1"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("address1","java.lang.String",e);
        }
        try {
            setAddress2(json.getString("address2"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("address2","java.lang.String",e);
        }
        try {
            setCity(json.getString("city"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("city","java.lang.String",e);
        }
        try {
            setPostalcode(json.getString("postalCode"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("postalCode","java.lang.String",e);
        }
        try {
            setLocationcoordinate(json.getString("locationCoordinate"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("locationCoordinate","java.lang.String",e);
        }
        try {
            String createdOnString = json.getString("createdOn");
            setCreatedon(createdOnString == null?null: LocalDateTime.parse(createdOnString));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("createdOn","java.time.LocalDateTime",e);
        }
        try {
            setCreatedby(json.getString("createdBy"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("createdBy","java.lang.String",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("serialNumber",getSerialnumber());
        json.put("type",getType());
        json.put("description",getDescription());
        json.put("image",getImage());
        json.put("name",getName());
        json.put("phone",getPhone());
        json.put("email",getEmail());
        json.put("website",getWebsite());
        json.put("ownerFirstName",getOwnerfirstname());
        json.put("ownerLastName",getOwnerlastname());
        json.put("country",getCountry());
        json.put("address1",getAddress1());
        json.put("address2",getAddress2());
        json.put("city",getCity());
        json.put("postalCode",getPostalcode());
        json.put("locationCoordinate",getLocationcoordinate());
        json.put("createdOn",getCreatedon()==null?null:getCreatedon().toString());
        json.put("createdBy",getCreatedby());
        return json;
    }

}
