/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetTime;

import javax.annotation.Generated;

import jooq.tables.TbUser;
import jooq.tables.interfaces.ITbUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This table contains user login credentials and assigned user role
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbUserRecord extends UpdatableRecordImpl<TbUserRecord> implements VertxPojo, Record11<Long, Long, String, String, String, String, String, String, String, OffsetTime, String>, ITbUser {

    private static final long serialVersionUID = 1783428935;

    /**
     * Setter for <code>public.tb_user.id</code>.
     */
    @Override
    public TbUserRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tb_user.role_id</code>.
     */
    @Override
    public TbUserRecord setRoleId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.role_id</code>.
     */
    @Override
    public Long getRoleId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.tb_user.first_name</code>.
     */
    @Override
    public TbUserRecord setFirstName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.first_name</code>.
     */
    @Override
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_user.last_name</code>.
     */
    @Override
    public TbUserRecord setLastName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.last_name</code>.
     */
    @Override
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_user.email</code>.
     */
    @Override
    public TbUserRecord setEmail(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.email</code>.
     */
    @Override
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tb_user.mobile</code>.
     */
    @Override
    public TbUserRecord setMobile(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.mobile</code>.
     */
    @Override
    public String getMobile() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tb_user.secret</code>.
     */
    @Override
    public TbUserRecord setSecret(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.secret</code>.
     */
    @Override
    public String getSecret() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tb_user.salt</code>.
     */
    @Override
    public TbUserRecord setSalt(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.salt</code>.
     */
    @Override
    public String getSalt() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.tb_user.company_code</code>.
     */
    @Override
    public TbUserRecord setCompanyCode(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.company_code</code>.
     */
    @Override
    public String getCompanyCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.tb_user.created_on</code>.
     */
    @Override
    public TbUserRecord setCreatedOn(OffsetTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.created_on</code>.
     */
    @Override
    public OffsetTime getCreatedOn() {
        return (OffsetTime) get(9);
    }

    /**
     * Setter for <code>public.tb_user.created_by</code>.
     */
    @Override
    public TbUserRecord setCreatedBy(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.created_by</code>.
     */
    @Override
    public String getCreatedBy() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Long, String, String, String, String, String, String, String, OffsetTime, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Long, String, String, String, String, String, String, String, OffsetTime, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TbUser.TB_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TbUser.TB_USER.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TbUser.TB_USER.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TbUser.TB_USER.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TbUser.TB_USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TbUser.TB_USER.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TbUser.TB_USER.SECRET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TbUser.TB_USER.SALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TbUser.TB_USER.COMPANY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetTime> field10() {
        return TbUser.TB_USER.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TbUser.TB_USER.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSecret();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCompanyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetTime component10() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSecret();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCompanyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetTime value10() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbUserRecord value2(Long value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbUserRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbUserRecord value4(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbUserRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbUserRecord value6(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbUserRecord value7(String value) {
        setSecret(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbUserRecord value8(String value) {
        setSalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbUserRecord value9(String value) {
        setCompanyCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbUserRecord value10(OffsetTime value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbUserRecord value11(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbUserRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, OffsetTime value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbUser from) {
        setId(from.getId());
        setRoleId(from.getRoleId());
        setFirstName(from.getFirstName());
        setLastName(from.getLastName());
        setEmail(from.getEmail());
        setMobile(from.getMobile());
        setSecret(from.getSecret());
        setSalt(from.getSalt());
        setCompanyCode(from.getCompanyCode());
        setCreatedOn(from.getCreatedOn());
        setCreatedBy(from.getCreatedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbUser> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbUserRecord
     */
    public TbUserRecord() {
        super(TbUser.TB_USER);
    }

    /**
     * Create a detached, initialised TbUserRecord
     */
    public TbUserRecord(Long id, Long roleId, String firstName, String lastName, String email, String mobile, String secret, String salt, String companyCode, OffsetTime createdOn, String createdBy) {
        super(TbUser.TB_USER);

        set(0, id);
        set(1, roleId);
        set(2, firstName);
        set(3, lastName);
        set(4, email);
        set(5, mobile);
        set(6, secret);
        set(7, salt);
        set(8, companyCode);
        set(9, createdOn);
        set(10, createdBy);
    }

    public TbUserRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
