/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbPropertyProfile;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbPropertyProfile implements VertxPojo, ITbPropertyProfile {

    private static final long serialVersionUID = 1266601482;

    private Long      id;
    private String    serialnumber;
    private String    type;
    private String    description;
    private String    image;
    private String    name;
    private String    phone;
    private String    email;
    private String    website;
    private String    ownerfirstname;
    private String    ownerlastname;
    private String    country;
    private String    address1;
    private String    address2;
    private String    city;
    private String    postalcode;
    private String    locationcoordinate;
    private Timestamp createdon;
    private String    createdby;
    private String    profilecode;

    public TbPropertyProfile() {}

    public TbPropertyProfile(ITbPropertyProfile value) {
        this.id = value.getId();
        this.serialnumber = value.getSerialnumber();
        this.type = value.getType();
        this.description = value.getDescription();
        this.image = value.getImage();
        this.name = value.getName();
        this.phone = value.getPhone();
        this.email = value.getEmail();
        this.website = value.getWebsite();
        this.ownerfirstname = value.getOwnerfirstname();
        this.ownerlastname = value.getOwnerlastname();
        this.country = value.getCountry();
        this.address1 = value.getAddress1();
        this.address2 = value.getAddress2();
        this.city = value.getCity();
        this.postalcode = value.getPostalcode();
        this.locationcoordinate = value.getLocationcoordinate();
        this.createdon = value.getCreatedon();
        this.createdby = value.getCreatedby();
        this.profilecode = value.getProfilecode();
    }

    public TbPropertyProfile(
        Long      id,
        String    serialnumber,
        String    type,
        String    description,
        String    image,
        String    name,
        String    phone,
        String    email,
        String    website,
        String    ownerfirstname,
        String    ownerlastname,
        String    country,
        String    address1,
        String    address2,
        String    city,
        String    postalcode,
        String    locationcoordinate,
        Timestamp createdon,
        String    createdby,
        String    profilecode
    ) {
        this.id = id;
        this.serialnumber = serialnumber;
        this.type = type;
        this.description = description;
        this.image = image;
        this.name = name;
        this.phone = phone;
        this.email = email;
        this.website = website;
        this.ownerfirstname = ownerfirstname;
        this.ownerlastname = ownerlastname;
        this.country = country;
        this.address1 = address1;
        this.address2 = address2;
        this.city = city;
        this.postalcode = postalcode;
        this.locationcoordinate = locationcoordinate;
        this.createdon = createdon;
        this.createdby = createdby;
        this.profilecode = profilecode;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbPropertyProfile setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getSerialnumber() {
        return this.serialnumber;
    }

    @Override
    public TbPropertyProfile setSerialnumber(String serialnumber) {
        this.serialnumber = serialnumber;
        return this;
    }

    @Override
    public String getType() {
        return this.type;
    }

    @Override
    public TbPropertyProfile setType(String type) {
        this.type = type;
        return this;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public TbPropertyProfile setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public String getImage() {
        return this.image;
    }

    @Override
    public TbPropertyProfile setImage(String image) {
        this.image = image;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public TbPropertyProfile setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getPhone() {
        return this.phone;
    }

    @Override
    public TbPropertyProfile setPhone(String phone) {
        this.phone = phone;
        return this;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public TbPropertyProfile setEmail(String email) {
        this.email = email;
        return this;
    }

    @Override
    public String getWebsite() {
        return this.website;
    }

    @Override
    public TbPropertyProfile setWebsite(String website) {
        this.website = website;
        return this;
    }

    @Override
    public String getOwnerfirstname() {
        return this.ownerfirstname;
    }

    @Override
    public TbPropertyProfile setOwnerfirstname(String ownerfirstname) {
        this.ownerfirstname = ownerfirstname;
        return this;
    }

    @Override
    public String getOwnerlastname() {
        return this.ownerlastname;
    }

    @Override
    public TbPropertyProfile setOwnerlastname(String ownerlastname) {
        this.ownerlastname = ownerlastname;
        return this;
    }

    @Override
    public String getCountry() {
        return this.country;
    }

    @Override
    public TbPropertyProfile setCountry(String country) {
        this.country = country;
        return this;
    }

    @Override
    public String getAddress1() {
        return this.address1;
    }

    @Override
    public TbPropertyProfile setAddress1(String address1) {
        this.address1 = address1;
        return this;
    }

    @Override
    public String getAddress2() {
        return this.address2;
    }

    @Override
    public TbPropertyProfile setAddress2(String address2) {
        this.address2 = address2;
        return this;
    }

    @Override
    public String getCity() {
        return this.city;
    }

    @Override
    public TbPropertyProfile setCity(String city) {
        this.city = city;
        return this;
    }

    @Override
    public String getPostalcode() {
        return this.postalcode;
    }

    @Override
    public TbPropertyProfile setPostalcode(String postalcode) {
        this.postalcode = postalcode;
        return this;
    }

    @Override
    public String getLocationcoordinate() {
        return this.locationcoordinate;
    }

    @Override
    public TbPropertyProfile setLocationcoordinate(String locationcoordinate) {
        this.locationcoordinate = locationcoordinate;
        return this;
    }

    @Override
    public Timestamp getCreatedon() {
        return this.createdon;
    }

    @Override
    public TbPropertyProfile setCreatedon(Timestamp createdon) {
        this.createdon = createdon;
        return this;
    }

    @Override
    public String getCreatedby() {
        return this.createdby;
    }

    @Override
    public TbPropertyProfile setCreatedby(String createdby) {
        this.createdby = createdby;
        return this;
    }

    @Override
    public String getProfilecode() {
        return this.profilecode;
    }

    @Override
    public TbPropertyProfile setProfilecode(String profilecode) {
        this.profilecode = profilecode;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbPropertyProfile (");

        sb.append(id);
        sb.append(", ").append(serialnumber);
        sb.append(", ").append(type);
        sb.append(", ").append(description);
        sb.append(", ").append(image);
        sb.append(", ").append(name);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);
        sb.append(", ").append(website);
        sb.append(", ").append(ownerfirstname);
        sb.append(", ").append(ownerlastname);
        sb.append(", ").append(country);
        sb.append(", ").append(address1);
        sb.append(", ").append(address2);
        sb.append(", ").append(city);
        sb.append(", ").append(postalcode);
        sb.append(", ").append(locationcoordinate);
        sb.append(", ").append(createdon);
        sb.append(", ").append(createdby);
        sb.append(", ").append(profilecode);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbPropertyProfile from) {
        setId(from.getId());
        setSerialnumber(from.getSerialnumber());
        setType(from.getType());
        setDescription(from.getDescription());
        setImage(from.getImage());
        setName(from.getName());
        setPhone(from.getPhone());
        setEmail(from.getEmail());
        setWebsite(from.getWebsite());
        setOwnerfirstname(from.getOwnerfirstname());
        setOwnerlastname(from.getOwnerlastname());
        setCountry(from.getCountry());
        setAddress1(from.getAddress1());
        setAddress2(from.getAddress2());
        setCity(from.getCity());
        setPostalcode(from.getPostalcode());
        setLocationcoordinate(from.getLocationcoordinate());
        setCreatedon(from.getCreatedon());
        setCreatedby(from.getCreatedby());
        setProfilecode(from.getProfilecode());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbPropertyProfile> E into(E into) {
        into.from(this);
        return into;
    }

    public TbPropertyProfile(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
