/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.TbAccomodation;
import jooq.tables.TbPropertyAmenity;
import jooq.tables.TbPropertyProfile;
import jooq.tables.TbUser;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TB_ACCOMODATION_PKEY = Indexes0.TB_ACCOMODATION_PKEY;
    public static final Index TB_PROPERTY_AMENITY_PKEY = Indexes0.TB_PROPERTY_AMENITY_PKEY;
    public static final Index TB_PROPERTY_PROFILE_PKEY = Indexes0.TB_PROPERTY_PROFILE_PKEY;
    public static final Index TB_USER_PKEY = Indexes0.TB_USER_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index TB_ACCOMODATION_PKEY = Internal.createIndex("tb_accomodation_pkey", TbAccomodation.TB_ACCOMODATION, new OrderField[] { TbAccomodation.TB_ACCOMODATION.ID }, true);
        public static Index TB_PROPERTY_AMENITY_PKEY = Internal.createIndex("tb_property_amenity_pkey", TbPropertyAmenity.TB_PROPERTY_AMENITY, new OrderField[] { TbPropertyAmenity.TB_PROPERTY_AMENITY.ID }, true);
        public static Index TB_PROPERTY_PROFILE_PKEY = Internal.createIndex("tb_property_profile_pkey", TbPropertyProfile.TB_PROPERTY_PROFILE, new OrderField[] { TbPropertyProfile.TB_PROPERTY_PROFILE.ID }, true);
        public static Index TB_USER_PKEY = Internal.createIndex("tb_user_pkey", TbUser.TB_USER, new OrderField[] { TbUser.TB_USER.ID }, true);
    }
}
