/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.TbAccomodation;
import jooq.tables.TbPropertyAmenity;
import jooq.tables.TbPropertyProfile;
import jooq.tables.TbUser;
import jooq.tables.records.TbAccomodationRecord;
import jooq.tables.records.TbPropertyAmenityRecord;
import jooq.tables.records.TbPropertyProfileRecord;
import jooq.tables.records.TbUserRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TbAccomodationRecord, Long> IDENTITY_TB_ACCOMODATION = Identities0.IDENTITY_TB_ACCOMODATION;
    public static final Identity<TbPropertyAmenityRecord, Long> IDENTITY_TB_PROPERTY_AMENITY = Identities0.IDENTITY_TB_PROPERTY_AMENITY;
    public static final Identity<TbPropertyProfileRecord, Long> IDENTITY_TB_PROPERTY_PROFILE = Identities0.IDENTITY_TB_PROPERTY_PROFILE;
    public static final Identity<TbUserRecord, Long> IDENTITY_TB_USER = Identities0.IDENTITY_TB_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TbAccomodationRecord> TB_ACCOMODATION_PKEY = UniqueKeys0.TB_ACCOMODATION_PKEY;
    public static final UniqueKey<TbPropertyAmenityRecord> TB_PROPERTY_AMENITY_PKEY = UniqueKeys0.TB_PROPERTY_AMENITY_PKEY;
    public static final UniqueKey<TbPropertyProfileRecord> TB_PROPERTY_PROFILE_PKEY = UniqueKeys0.TB_PROPERTY_PROFILE_PKEY;
    public static final UniqueKey<TbUserRecord> TB_USER_PKEY = UniqueKeys0.TB_USER_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<TbAccomodationRecord, Long> IDENTITY_TB_ACCOMODATION = Internal.createIdentity(TbAccomodation.TB_ACCOMODATION, TbAccomodation.TB_ACCOMODATION.ID);
        public static Identity<TbPropertyAmenityRecord, Long> IDENTITY_TB_PROPERTY_AMENITY = Internal.createIdentity(TbPropertyAmenity.TB_PROPERTY_AMENITY, TbPropertyAmenity.TB_PROPERTY_AMENITY.ID);
        public static Identity<TbPropertyProfileRecord, Long> IDENTITY_TB_PROPERTY_PROFILE = Internal.createIdentity(TbPropertyProfile.TB_PROPERTY_PROFILE, TbPropertyProfile.TB_PROPERTY_PROFILE.ID);
        public static Identity<TbUserRecord, Long> IDENTITY_TB_USER = Internal.createIdentity(TbUser.TB_USER, TbUser.TB_USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<TbAccomodationRecord> TB_ACCOMODATION_PKEY = Internal.createUniqueKey(TbAccomodation.TB_ACCOMODATION, "tb_accomodation_pkey", TbAccomodation.TB_ACCOMODATION.ID);
        public static final UniqueKey<TbPropertyAmenityRecord> TB_PROPERTY_AMENITY_PKEY = Internal.createUniqueKey(TbPropertyAmenity.TB_PROPERTY_AMENITY, "tb_property_amenity_pkey", TbPropertyAmenity.TB_PROPERTY_AMENITY.ID);
        public static final UniqueKey<TbPropertyProfileRecord> TB_PROPERTY_PROFILE_PKEY = Internal.createUniqueKey(TbPropertyProfile.TB_PROPERTY_PROFILE, "tb_property_profile_pkey", TbPropertyProfile.TB_PROPERTY_PROFILE.ID);
        public static final UniqueKey<TbUserRecord> TB_USER_PKEY = Internal.createUniqueKey(TbUser.TB_USER, "tb_user_pkey", TbUser.TB_USER.ID);
    }
}
