/*
 * This file is generated by jOOQ.
 */
package jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.tables.TbAccomodation;
import jooq.tables.TbPropertyAmenity;
import jooq.tables.TbPropertyProfile;
import jooq.tables.TbUser;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -2122616028;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.tb_accomodation</code>.
     */
    public final TbAccomodation TB_ACCOMODATION = TbAccomodation.TB_ACCOMODATION;

    /**
     * The table <code>public.tb_property_amenity</code>.
     */
    public final TbPropertyAmenity TB_PROPERTY_AMENITY = TbPropertyAmenity.TB_PROPERTY_AMENITY;

    /**
     * The table <code>public.tb_property_profile</code>.
     */
    public final TbPropertyProfile TB_PROPERTY_PROFILE = TbPropertyProfile.TB_PROPERTY_PROFILE;

    /**
     * The table <code>public.tb_user</code>.
     */
    public final TbUser TB_USER = TbUser.TB_USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.TB_ACCOMODATION_ID_SEQ,
            Sequences.TB_PROPERTY_AMENITY_ID_SEQ,
            Sequences.TB_PROPERTY_PROFILE_ID_SEQ,
            Sequences.TB_USER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TbAccomodation.TB_ACCOMODATION,
            TbPropertyAmenity.TB_PROPERTY_AMENITY,
            TbPropertyProfile.TB_PROPERTY_PROFILE,
            TbUser.TB_USER);
    }
}
