/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.routines.FnGetNow;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.fn_get_now</code>
     */
    public static String fnGetNow(Configuration configuration) {
        FnGetNow f = new FnGetNow();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.fn_get_now</code> as a field.
     */
    public static Field<String> fnGetNow() {
        FnGetNow f = new FnGetNow();

        return f.asField();
    }
}
