/*
 * This file is generated by jOOQ.
 */
package jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.tb_accomodation_id_seq</code>
     */
    public static final Sequence<Long> TB_ACCOMODATION_ID_SEQ = Internal.createSequence("tb_accomodation_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.tb_property_amenity_id_seq</code>
     */
    public static final Sequence<Long> TB_PROPERTY_AMENITY_ID_SEQ = Internal.createSequence("tb_property_amenity_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.tb_property_profile_id_seq</code>
     */
    public static final Sequence<Long> TB_PROPERTY_PROFILE_ID_SEQ = Internal.createSequence("tb_property_profile_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.tb_user_id_seq</code>
     */
    public static final Sequence<Long> TB_USER_ID_SEQ = Internal.createSequence("tb_user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
