/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.TbAccomodation;
import jooq.tables.TbPropertyAmenity;
import jooq.tables.TbPropertyProfile;
import jooq.tables.TbUser;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.tb_accomodation</code>.
     */
    public static final TbAccomodation TB_ACCOMODATION = TbAccomodation.TB_ACCOMODATION;

    /**
     * The table <code>public.tb_property_amenity</code>.
     */
    public static final TbPropertyAmenity TB_PROPERTY_AMENITY = TbPropertyAmenity.TB_PROPERTY_AMENITY;

    /**
     * The table <code>public.tb_property_profile</code>.
     */
    public static final TbPropertyProfile TB_PROPERTY_PROFILE = TbPropertyProfile.TB_PROPERTY_PROFILE;

    /**
     * The table <code>public.tb_user</code>.
     */
    public static final TbUser TB_USER = TbUser.TB_USER;
}
