/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.TbUser;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TB_USER_EMAIL_KEY = Indexes0.TB_USER_EMAIL_KEY;
    public static final Index TB_USER_MOBILE_KEY = Indexes0.TB_USER_MOBILE_KEY;
    public static final Index TB_USER_PKEY = Indexes0.TB_USER_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index TB_USER_EMAIL_KEY = Internal.createIndex("tb_user_email_key", TbUser.TB_USER, new OrderField[] { TbUser.TB_USER.EMAIL }, true);
        public static Index TB_USER_MOBILE_KEY = Internal.createIndex("tb_user_mobile_key", TbUser.TB_USER, new OrderField[] { TbUser.TB_USER.MOBILE }, true);
        public static Index TB_USER_PKEY = Internal.createIndex("tb_user_pkey", TbUser.TB_USER, new OrderField[] { TbUser.TB_USER.ID }, true);
    }
}
