/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetTime;

import javax.annotation.Generated;

import jooq.tables.interfaces.ITbUser;


/**
 * This table contains user login credentials and assigned user role
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbUser implements VertxPojo, ITbUser {

    private static final long serialVersionUID = 1204123502;

    private Long       id;
    private Long       roleId;
    private String     firstName;
    private String     lastName;
    private String     email;
    private String     mobile;
    private String     secret;
    private String     salt;
    private String     companyCode;
    private OffsetTime createdOn;
    private String     createdBy;

    public TbUser() {}

    public TbUser(ITbUser value) {
        this.id = value.getId();
        this.roleId = value.getRoleId();
        this.firstName = value.getFirstName();
        this.lastName = value.getLastName();
        this.email = value.getEmail();
        this.mobile = value.getMobile();
        this.secret = value.getSecret();
        this.salt = value.getSalt();
        this.companyCode = value.getCompanyCode();
        this.createdOn = value.getCreatedOn();
        this.createdBy = value.getCreatedBy();
    }

    public TbUser(
        Long       id,
        Long       roleId,
        String     firstName,
        String     lastName,
        String     email,
        String     mobile,
        String     secret,
        String     salt,
        String     companyCode,
        OffsetTime createdOn,
        String     createdBy
    ) {
        this.id = id;
        this.roleId = roleId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.mobile = mobile;
        this.secret = secret;
        this.salt = salt;
        this.companyCode = companyCode;
        this.createdOn = createdOn;
        this.createdBy = createdBy;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TbUser setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public Long getRoleId() {
        return this.roleId;
    }

    @Override
    public TbUser setRoleId(Long roleId) {
        this.roleId = roleId;
        return this;
    }

    @Override
    public String getFirstName() {
        return this.firstName;
    }

    @Override
    public TbUser setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    @Override
    public String getLastName() {
        return this.lastName;
    }

    @Override
    public TbUser setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public TbUser setEmail(String email) {
        this.email = email;
        return this;
    }

    @Override
    public String getMobile() {
        return this.mobile;
    }

    @Override
    public TbUser setMobile(String mobile) {
        this.mobile = mobile;
        return this;
    }

    @Override
    public String getSecret() {
        return this.secret;
    }

    @Override
    public TbUser setSecret(String secret) {
        this.secret = secret;
        return this;
    }

    @Override
    public String getSalt() {
        return this.salt;
    }

    @Override
    public TbUser setSalt(String salt) {
        this.salt = salt;
        return this;
    }

    @Override
    public String getCompanyCode() {
        return this.companyCode;
    }

    @Override
    public TbUser setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
        return this;
    }

    @Override
    public OffsetTime getCreatedOn() {
        return this.createdOn;
    }

    @Override
    public TbUser setCreatedOn(OffsetTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    @Override
    public TbUser setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbUser (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(email);
        sb.append(", ").append(mobile);
        sb.append(", ").append(secret);
        sb.append(", ").append(salt);
        sb.append(", ").append(companyCode);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(createdBy);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbUser from) {
        setId(from.getId());
        setRoleId(from.getRoleId());
        setFirstName(from.getFirstName());
        setLastName(from.getLastName());
        setEmail(from.getEmail());
        setMobile(from.getMobile());
        setSecret(from.getSecret());
        setSalt(from.getSalt());
        setCompanyCode(from.getCompanyCode());
        setCreatedOn(from.getCreatedOn());
        setCreatedBy(from.getCreatedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbUser> E into(E into) {
        into.from(this);
        return into;
    }

    public TbUser(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
