/*
 * This file is generated by jOOQ.
 */
package jooq.routines;


import jooq.Public;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FnGetNow extends AbstractRoutine<String> {

    private static final long serialVersionUID = -1733058867;

    /**
     * The parameter <code>public.fn_get_now.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * Create a new routine call instance
     */
    public FnGetNow() {
        super("fn_get_now", Public.PUBLIC, org.jooq.impl.SQLDataType.VARCHAR);

        setReturnParameter(RETURN_VALUE);
    }
}
