/*
 * This file is generated by jOOQ.
 */
package jooq.routines;


import java.math.BigDecimal;

import javax.annotation.Generated;

import jooq.Public;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HiLo extends AbstractRoutine<Void> {

    private static final long serialVersionUID = 116181103;

    /**
     * The parameter <code>public.hi_lo.a</code>.
     */
    public static final Parameter<BigDecimal> A = Internal.createParameter("a", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * The parameter <code>public.hi_lo.b</code>.
     */
    public static final Parameter<BigDecimal> B = Internal.createParameter("b", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * The parameter <code>public.hi_lo.c</code>.
     */
    public static final Parameter<BigDecimal> C = Internal.createParameter("c", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * The parameter <code>public.hi_lo.hi</code>.
     */
    public static final Parameter<BigDecimal> HI = Internal.createParameter("hi", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * The parameter <code>public.hi_lo.lo</code>.
     */
    public static final Parameter<BigDecimal> LO = Internal.createParameter("lo", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * Create a new routine call instance
     */
    public HiLo() {
        super("hi_lo", Public.PUBLIC);

        addInParameter(A);
        addInParameter(B);
        addInParameter(C);
        addOutParameter(HI);
        addOutParameter(LO);
    }

    /**
     * Set the <code>a</code> parameter IN value to the routine
     */
    public void setA(BigDecimal value) {
        setValue(A, value);
    }

    /**
     * Set the <code>b</code> parameter IN value to the routine
     */
    public void setB(BigDecimal value) {
        setValue(B, value);
    }

    /**
     * Set the <code>c</code> parameter IN value to the routine
     */
    public void setC(BigDecimal value) {
        setValue(C, value);
    }

    /**
     * Get the <code>hi</code> parameter OUT value from the routine
     */
    public BigDecimal getHi() {
        return get(HI);
    }

    /**
     * Get the <code>lo</code> parameter OUT value from the routine
     */
    public BigDecimal getLo() {
        return get(LO);
    }
}
