/*
 * This file is generated by jOOQ.
 */
package jooq.routines;


import javax.annotation.Generated;

import jooq.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Decremental extends AbstractRoutine<Long> {

    private static final long serialVersionUID = -545960800;

    /**
     * The parameter <code>public.decremental.RETURN_VALUE</code>.
     */
    public static final Parameter<Long> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>public.decremental.val</code>.
     */
    public static final Parameter<Long> VAL = Internal.createParameter("val", org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), true, false);

    /**
     * Create a new routine call instance
     */
    public Decremental() {
        super("decremental", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

        setReturnParameter(RETURN_VALUE);
        addInParameter(VAL);
    }

    /**
     * Set the <code>val</code> parameter IN value to the routine
     */
    public void setVal(Long value) {
        setValue(VAL, value);
    }

    /**
     * Set the <code>val</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public Decremental setVal(Field<Long> field) {
        setField(VAL, field);
        return this;
    }
}
