/*
 * This file is generated by jOOQ.
 */
package jooq.routines;


import javax.annotation.Generated;

import jooq.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Incremental extends AbstractRoutine<Integer> {

    private static final long serialVersionUID = -667506360;

    /**
     * The parameter <code>public.incremental.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>public.incremental.val</code>.
     */
    public static final Parameter<Integer> VAL = Internal.createParameter("val", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public Incremental() {
        super("incremental", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
        addInParameter(VAL);
    }

    /**
     * Set the <code>val</code> parameter IN value to the routine
     */
    public void setVal(Integer value) {
        setValue(VAL, value);
    }

    /**
     * Set the <code>val</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public Incremental setVal(Field<Integer> field) {
        setField(VAL, field);
        return this;
    }
}
