/*
 * This file is generated by jOOQ.
 */
package jooq.routines;


import javax.annotation.Generated;

import jooq.Public;

import org.jooq.Parameter;
import org.jooq.Record;
import org.jooq.Result;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShowUsers extends AbstractRoutine<Result<Record>> {

    private static final long serialVersionUID = -563458264;

    /**
     * The parameter <code>public.show_users.RETURN_VALUE</code>.
     */
    public static final Parameter<Result<Record>> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.RESULT, false, false);

    /**
     * Create a new routine call instance
     */
    public ShowUsers() {
        super("show_users", Public.PUBLIC, org.jooq.impl.SQLDataType.RESULT);

        setReturnParameter(RETURN_VALUE);
    }
}
