/*
 * This file is generated by jOOQ.
 */
package jooq.routines;


import java.math.BigDecimal;

import javax.annotation.Generated;

import jooq.Public;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Square extends AbstractRoutine<Void> {

    private static final long serialVersionUID = -315248101;

    /**
     * The parameter <code>public.square.a</code>.
     */
    public static final Parameter<BigDecimal> A = Internal.createParameter("a", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * Create a new routine call instance
     */
    public Square() {
        super("square", Public.PUBLIC);

        addInOutParameter(A);
    }

    /**
     * Set the <code>a</code> parameter IN value to the routine
     */
    public void setA(BigDecimal value) {
        setValue(A, value);
    }

    /**
     * Get the <code>a</code> parameter OUT value from the routine
     */
    public BigDecimal getA() {
        return get(A);
    }
}
