/*
 * This file is generated by jOOQ.
 */
package jooq.routines;


import java.math.BigDecimal;

import javax.annotation.Generated;

import jooq.Public;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SumAvg extends AbstractRoutine<Void> {

    private static final long serialVersionUID = -1291051320;

    /**
     * The parameter <code>public.sum_avg.list</code>.
     */
    public static final Parameter<BigDecimal[]> LIST = Internal.createParameter("list", org.jooq.impl.SQLDataType.NUMERIC.getArrayDataType(), false, false);

    /**
     * The parameter <code>public.sum_avg.total</code>.
     */
    public static final Parameter<BigDecimal> TOTAL = Internal.createParameter("total", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * The parameter <code>public.sum_avg.average</code>.
     */
    public static final Parameter<BigDecimal> AVERAGE = Internal.createParameter("average", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * Create a new routine call instance
     */
    public SumAvg() {
        super("sum_avg", Public.PUBLIC);

        addInParameter(LIST);
        addOutParameter(TOTAL);
        addOutParameter(AVERAGE);
    }

    /**
     * Set the <code>list</code> parameter IN value to the routine
     */
    public void setList(BigDecimal... value) {
        setValue(LIST, value);
    }

    /**
     * Get the <code>total</code> parameter OUT value from the routine
     */
    public BigDecimal getTotal() {
        return get(TOTAL);
    }

    /**
     * Get the <code>average</code> parameter OUT value from the routine
     */
    public BigDecimal getAverage() {
        return get(AVERAGE);
    }
}
