/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.async.AbstractAsyncVertxDAO;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import jooq.tables.TbPropertyAmenity;
import jooq.tables.records.TbPropertyAmenityRecord;

import org.jooq.Configuration;


import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.async.AsyncClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbPropertyAmenityDao extends AbstractAsyncVertxDAO<TbPropertyAmenityRecord, jooq.tables.pojos.TbPropertyAmenity, Long, Future<List<jooq.tables.pojos.TbPropertyAmenity>>, Future<jooq.tables.pojos.TbPropertyAmenity>, Future<Integer>, Future<Long>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<TbPropertyAmenityRecord,jooq.tables.pojos.TbPropertyAmenity,Long> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the MYSQL types or POSTGRES.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public TbPropertyAmenityDao(Configuration configuration, io.vertx.ext.asyncsql.AsyncSQLClient delegate) {
        super(TbPropertyAmenity.TB_PROPERTY_AMENITY, jooq.tables.pojos.TbPropertyAmenity.class, new AsyncClassicQueryExecutor<TbPropertyAmenityRecord,jooq.tables.pojos.TbPropertyAmenity,Long>(configuration,delegate,jooq.tables.pojos.TbPropertyAmenity::new, TbPropertyAmenity.TB_PROPERTY_AMENITY));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(jooq.tables.pojos.TbPropertyAmenity object) {
        return object.getId();
    }

    /**
     * Find records that have <code>serialNumber IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbPropertyAmenity>> findManyBySerialnumber(List<String> values) {
        return findManyByCondition(TbPropertyAmenity.TB_PROPERTY_AMENITY.SERIALNUMBER.in(values));
    }

    /**
     * Find records that have <code>amenity IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbPropertyAmenity>> findManyByAmenity(List<String> values) {
        return findManyByCondition(TbPropertyAmenity.TB_PROPERTY_AMENITY.AMENITY.in(values));
    }

    /**
     * Find records that have <code>status IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbPropertyAmenity>> findManyByStatus(List<String> values) {
        return findManyByCondition(TbPropertyAmenity.TB_PROPERTY_AMENITY.STATUS.in(values));
    }

    /**
     * Find records that have <code>createdOn IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbPropertyAmenity>> findManyByCreatedon(List<Timestamp> values) {
        return findManyByCondition(TbPropertyAmenity.TB_PROPERTY_AMENITY.CREATEDON.in(values));
    }

    /**
     * Find records that have <code>createdBy IN (values)</code> asynchronously
     */
    public Future<List<jooq.tables.pojos.TbPropertyAmenity>> findManyByCreatedby(List<String> values) {
        return findManyByCondition(TbPropertyAmenity.TB_PROPERTY_AMENITY.CREATEDBY.in(values));
    }

    @Override
    public AsyncClassicQueryExecutor<TbPropertyAmenityRecord,jooq.tables.pojos.TbPropertyAmenity,Long> queryExecutor(){
        return (AsyncClassicQueryExecutor<TbPropertyAmenityRecord,jooq.tables.pojos.TbPropertyAmenity,Long>) super.queryExecutor();
    }

    @Override
    protected java.util.function.Function<Object,Long> keyConverter(){
        return lastId -> Long.valueOf(((io.vertx.core.json.JsonArray)lastId).getLong(0).longValue());
    }
}
