/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.Indexes;
import jooq.Keys;
import jooq.Public;
import jooq.tables.records.TbPropertyProfileRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbPropertyProfile extends TableImpl<TbPropertyProfileRecord> {

    private static final long serialVersionUID = -2097687732;

    /**
     * The reference instance of <code>public.tb_property_profile</code>
     */
    public static final TbPropertyProfile TB_PROPERTY_PROFILE = new TbPropertyProfile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbPropertyProfileRecord> getRecordType() {
        return TbPropertyProfileRecord.class;
    }

    /**
     * The column <code>public.tb_property_profile.id</code>.
     */
    public final TableField<TbPropertyProfileRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("nextval('tb_property_profile_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.tb_property_profile.serialNumber</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> SERIALNUMBER = createField("serialNumber", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.tb_property_profile.type</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_property_profile.description</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.tb_property_profile.image</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> IMAGE = createField("image", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.tb_property_profile.name</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_property_profile.phone</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.tb_property_profile.email</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_property_profile.website</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> WEBSITE = createField("website", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_property_profile.ownerFirstName</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> OWNERFIRSTNAME = createField("ownerFirstName", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_property_profile.ownerLastName</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> OWNERLASTNAME = createField("ownerLastName", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_property_profile.country</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_property_profile.address1</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> ADDRESS1 = createField("address1", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_property_profile.address2</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> ADDRESS2 = createField("address2", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_property_profile.city</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_property_profile.postalCode</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> POSTALCODE = createField("postalCode", org.jooq.impl.SQLDataType.VARCHAR(6), this, "");

    /**
     * The column <code>public.tb_property_profile.locationCoordinate</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> LOCATIONCOORDINATE = createField("locationCoordinate", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_property_profile.createdOn</code>.
     */
    public final TableField<TbPropertyProfileRecord, Timestamp> CREATEDON = createField("createdOn", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>public.tb_property_profile.createdBy</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> CREATEDBY = createField("createdBy", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.tb_property_profile.profileCode</code>.
     */
    public final TableField<TbPropertyProfileRecord, String> PROFILECODE = createField("profileCode", org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * Create a <code>public.tb_property_profile</code> table reference
     */
    public TbPropertyProfile() {
        this(DSL.name("tb_property_profile"), null);
    }

    /**
     * Create an aliased <code>public.tb_property_profile</code> table reference
     */
    public TbPropertyProfile(String alias) {
        this(DSL.name(alias), TB_PROPERTY_PROFILE);
    }

    /**
     * Create an aliased <code>public.tb_property_profile</code> table reference
     */
    public TbPropertyProfile(Name alias) {
        this(alias, TB_PROPERTY_PROFILE);
    }

    private TbPropertyProfile(Name alias, Table<TbPropertyProfileRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbPropertyProfile(Name alias, Table<TbPropertyProfileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TbPropertyProfile(Table<O> child, ForeignKey<O, TbPropertyProfileRecord> key) {
        super(child, key, TB_PROPERTY_PROFILE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TB_PROPERTY_PROFILE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TbPropertyProfileRecord, Long> getIdentity() {
        return Keys.IDENTITY_TB_PROPERTY_PROFILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TbPropertyProfileRecord> getPrimaryKey() {
        return Keys.TB_PROPERTY_PROFILE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TbPropertyProfileRecord>> getKeys() {
        return Arrays.<UniqueKey<TbPropertyProfileRecord>>asList(Keys.TB_PROPERTY_PROFILE_PKEY, Keys.TB_PROPERTY_PROFILE_PROFILECODE_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfile as(String alias) {
        return new TbPropertyProfile(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfile as(Name alias) {
        return new TbPropertyProfile(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbPropertyProfile rename(String name) {
        return new TbPropertyProfile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbPropertyProfile rename(Name name) {
        return new TbPropertyProfile(name, null);
    }
}
