/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetDateTime;

import javax.annotation.Generated;

import jooq.tables.TbAccomodation;
import jooq.tables.interfaces.ITbAccomodation;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbAccomodationRecord extends UpdatableRecordImpl<TbAccomodationRecord> implements VertxPojo, Record9<Long, String, String, String, String, Integer, Integer, OffsetDateTime, String>, ITbAccomodation {

    private static final long serialVersionUID = 1290466674;

    /**
     * Setter for <code>public.tb_accomodation.id</code>.
     */
    @Override
    public TbAccomodationRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_accomodation.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tb_accomodation.serialNumber</code>.
     */
    @Override
    public TbAccomodationRecord setSerialnumber(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_accomodation.serialNumber</code>.
     */
    @Override
    public String getSerialnumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_accomodation.name</code>.
     */
    @Override
    public TbAccomodationRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_accomodation.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_accomodation.abbrevation</code>.
     */
    @Override
    public TbAccomodationRecord setAbbrevation(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_accomodation.abbrevation</code>.
     */
    @Override
    public String getAbbrevation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_accomodation.units</code>.
     */
    @Override
    public TbAccomodationRecord setUnits(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_accomodation.units</code>.
     */
    @Override
    public String getUnits() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tb_accomodation.dormBedsPerRoom</code>.
     */
    @Override
    public TbAccomodationRecord setDormbedsperroom(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_accomodation.dormBedsPerRoom</code>.
     */
    @Override
    public Integer getDormbedsperroom() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tb_accomodation.totalAccomodation</code>.
     */
    @Override
    public TbAccomodationRecord setTotalaccomodation(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_accomodation.totalAccomodation</code>.
     */
    @Override
    public Integer getTotalaccomodation() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.tb_accomodation.createdOn</code>.
     */
    @Override
    public TbAccomodationRecord setCreatedon(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_accomodation.createdOn</code>.
     */
    @Override
    public OffsetDateTime getCreatedon() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.tb_accomodation.createdBy</code>.
     */
    @Override
    public TbAccomodationRecord setCreatedby(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_accomodation.createdBy</code>.
     */
    @Override
    public String getCreatedby() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, Integer, Integer, OffsetDateTime, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, Integer, Integer, OffsetDateTime, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TbAccomodation.TB_ACCOMODATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbAccomodation.TB_ACCOMODATION.SERIALNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TbAccomodation.TB_ACCOMODATION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TbAccomodation.TB_ACCOMODATION.ABBREVATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TbAccomodation.TB_ACCOMODATION.UNITS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TbAccomodation.TB_ACCOMODATION.DORMBEDSPERROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TbAccomodation.TB_ACCOMODATION.TOTALACCOMODATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field8() {
        return TbAccomodation.TB_ACCOMODATION.CREATEDON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TbAccomodation.TB_ACCOMODATION.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSerialnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAbbrevation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUnits();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getDormbedsperroom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getTotalaccomodation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component8() {
        return getCreatedon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSerialnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAbbrevation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUnits();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getDormbedsperroom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getTotalaccomodation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value8() {
        return getCreatedon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAccomodationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAccomodationRecord value2(String value) {
        setSerialnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAccomodationRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAccomodationRecord value4(String value) {
        setAbbrevation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAccomodationRecord value5(String value) {
        setUnits(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAccomodationRecord value6(Integer value) {
        setDormbedsperroom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAccomodationRecord value7(Integer value) {
        setTotalaccomodation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAccomodationRecord value8(OffsetDateTime value) {
        setCreatedon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAccomodationRecord value9(String value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAccomodationRecord values(Long value1, String value2, String value3, String value4, String value5, Integer value6, Integer value7, OffsetDateTime value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbAccomodation from) {
        setId(from.getId());
        setSerialnumber(from.getSerialnumber());
        setName(from.getName());
        setAbbrevation(from.getAbbrevation());
        setUnits(from.getUnits());
        setDormbedsperroom(from.getDormbedsperroom());
        setTotalaccomodation(from.getTotalaccomodation());
        setCreatedon(from.getCreatedon());
        setCreatedby(from.getCreatedby());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbAccomodation> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbAccomodationRecord
     */
    public TbAccomodationRecord() {
        super(TbAccomodation.TB_ACCOMODATION);
    }

    /**
     * Create a detached, initialised TbAccomodationRecord
     */
    public TbAccomodationRecord(Long id, String serialnumber, String name, String abbrevation, String units, Integer dormbedsperroom, Integer totalaccomodation, OffsetDateTime createdon, String createdby) {
        super(TbAccomodation.TB_ACCOMODATION);

        set(0, id);
        set(1, serialnumber);
        set(2, name);
        set(3, abbrevation);
        set(4, units);
        set(5, dormbedsperroom);
        set(6, totalaccomodation);
        set(7, createdon);
        set(8, createdby);
    }

    public TbAccomodationRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
