/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import jooq.tables.TbPropertyProfile;
import jooq.tables.interfaces.ITbPropertyProfile;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbPropertyProfileRecord extends UpdatableRecordImpl<TbPropertyProfileRecord> implements VertxPojo, Record20<Long, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, String, String>, ITbPropertyProfile {

    private static final long serialVersionUID = 1022904161;

    /**
     * Setter for <code>public.tb_property_profile.id</code>.
     */
    @Override
    public TbPropertyProfileRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tb_property_profile.serialNumber</code>.
     */
    @Override
    public TbPropertyProfileRecord setSerialnumber(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.serialNumber</code>.
     */
    @Override
    public String getSerialnumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_property_profile.type</code>.
     */
    @Override
    public TbPropertyProfileRecord setType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.type</code>.
     */
    @Override
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_property_profile.description</code>.
     */
    @Override
    public TbPropertyProfileRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.description</code>.
     */
    @Override
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_property_profile.image</code>.
     */
    @Override
    public TbPropertyProfileRecord setImage(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.image</code>.
     */
    @Override
    public String getImage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tb_property_profile.name</code>.
     */
    @Override
    public TbPropertyProfileRecord setName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tb_property_profile.phone</code>.
     */
    @Override
    public TbPropertyProfileRecord setPhone(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.phone</code>.
     */
    @Override
    public String getPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tb_property_profile.email</code>.
     */
    @Override
    public TbPropertyProfileRecord setEmail(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.email</code>.
     */
    @Override
    public String getEmail() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.tb_property_profile.website</code>.
     */
    @Override
    public TbPropertyProfileRecord setWebsite(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.website</code>.
     */
    @Override
    public String getWebsite() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.tb_property_profile.ownerFirstName</code>.
     */
    @Override
    public TbPropertyProfileRecord setOwnerfirstname(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.ownerFirstName</code>.
     */
    @Override
    public String getOwnerfirstname() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.tb_property_profile.ownerLastName</code>.
     */
    @Override
    public TbPropertyProfileRecord setOwnerlastname(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.ownerLastName</code>.
     */
    @Override
    public String getOwnerlastname() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.tb_property_profile.country</code>.
     */
    @Override
    public TbPropertyProfileRecord setCountry(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.country</code>.
     */
    @Override
    public String getCountry() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.tb_property_profile.address1</code>.
     */
    @Override
    public TbPropertyProfileRecord setAddress1(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.address1</code>.
     */
    @Override
    public String getAddress1() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.tb_property_profile.address2</code>.
     */
    @Override
    public TbPropertyProfileRecord setAddress2(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.address2</code>.
     */
    @Override
    public String getAddress2() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.tb_property_profile.city</code>.
     */
    @Override
    public TbPropertyProfileRecord setCity(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.city</code>.
     */
    @Override
    public String getCity() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.tb_property_profile.postalCode</code>.
     */
    @Override
    public TbPropertyProfileRecord setPostalcode(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.postalCode</code>.
     */
    @Override
    public String getPostalcode() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.tb_property_profile.locationCoordinate</code>.
     */
    @Override
    public TbPropertyProfileRecord setLocationcoordinate(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.locationCoordinate</code>.
     */
    @Override
    public String getLocationcoordinate() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.tb_property_profile.createdOn</code>.
     */
    @Override
    public TbPropertyProfileRecord setCreatedon(Timestamp value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.createdOn</code>.
     */
    @Override
    public Timestamp getCreatedon() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>public.tb_property_profile.createdBy</code>.
     */
    @Override
    public TbPropertyProfileRecord setCreatedby(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.createdBy</code>.
     */
    @Override
    public String getCreatedby() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.tb_property_profile.profileCode</code>.
     */
    @Override
    public TbPropertyProfileRecord setProfilecode(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_property_profile.profileCode</code>.
     */
    @Override
    public String getProfilecode() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Long, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, String, String> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Long, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Timestamp, String, String> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.SERIALNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.IMAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.WEBSITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.OWNERFIRSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.OWNERLASTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.ADDRESS1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.ADDRESS2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.POSTALCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.LOCATIONCOORDINATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.CREATEDON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.CREATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return TbPropertyProfile.TB_PROPERTY_PROFILE.PROFILECODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSerialnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getOwnerfirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getOwnerlastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getAddress1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getAddress2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getPostalcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getLocationcoordinate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component18() {
        return getCreatedon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component19() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component20() {
        return getProfilecode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSerialnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getOwnerfirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getOwnerlastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getAddress1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getAddress2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getPostalcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getLocationcoordinate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getCreatedon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getProfilecode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value2(String value) {
        setSerialnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value5(String value) {
        setImage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value6(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value7(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value8(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value9(String value) {
        setWebsite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value10(String value) {
        setOwnerfirstname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value11(String value) {
        setOwnerlastname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value12(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value13(String value) {
        setAddress1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value14(String value) {
        setAddress2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value15(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value16(String value) {
        setPostalcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value17(String value) {
        setLocationcoordinate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value18(Timestamp value) {
        setCreatedon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value19(String value) {
        setCreatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord value20(String value) {
        setProfilecode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbPropertyProfileRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, Timestamp value18, String value19, String value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITbPropertyProfile from) {
        setId(from.getId());
        setSerialnumber(from.getSerialnumber());
        setType(from.getType());
        setDescription(from.getDescription());
        setImage(from.getImage());
        setName(from.getName());
        setPhone(from.getPhone());
        setEmail(from.getEmail());
        setWebsite(from.getWebsite());
        setOwnerfirstname(from.getOwnerfirstname());
        setOwnerlastname(from.getOwnerlastname());
        setCountry(from.getCountry());
        setAddress1(from.getAddress1());
        setAddress2(from.getAddress2());
        setCity(from.getCity());
        setPostalcode(from.getPostalcode());
        setLocationcoordinate(from.getLocationcoordinate());
        setCreatedon(from.getCreatedon());
        setCreatedby(from.getCreatedby());
        setProfilecode(from.getProfilecode());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITbPropertyProfile> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbPropertyProfileRecord
     */
    public TbPropertyProfileRecord() {
        super(TbPropertyProfile.TB_PROPERTY_PROFILE);
    }

    /**
     * Create a detached, initialised TbPropertyProfileRecord
     */
    public TbPropertyProfileRecord(Long id, String serialnumber, String type, String description, String image, String name, String phone, String email, String website, String ownerfirstname, String ownerlastname, String country, String address1, String address2, String city, String postalcode, String locationcoordinate, Timestamp createdon, String createdby, String profilecode) {
        super(TbPropertyProfile.TB_PROPERTY_PROFILE);

        set(0, id);
        set(1, serialnumber);
        set(2, type);
        set(3, description);
        set(4, image);
        set(5, name);
        set(6, phone);
        set(7, email);
        set(8, website);
        set(9, ownerfirstname);
        set(10, ownerlastname);
        set(11, country);
        set(12, address1);
        set(13, address2);
        set(14, city);
        set(15, postalcode);
        set(16, locationcoordinate);
        set(17, createdon);
        set(18, createdby);
        set(19, profilecode);
    }

    public TbPropertyProfileRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
