/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.OffsetDateTime;

import jooq.tables.TbUser;
import jooq.tables.interfaces.ITbUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbUserRecord extends UpdatableRecordImpl<TbUserRecord> implements VertxPojo, Record11<Long, String, String, String, String, String, String, String, String, OffsetDateTime, String>, ITbUser {

    private static final long serialVersionUID = 565433478;

    /**
     * Setter for <code>public.tb_user.id</code>.
     */
    @Override
    public TbUserRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tb_user.roleId</code>.
     */
    @Override
    public TbUserRecord setRoleid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.roleId</code>.
     */
    @Override
    public String getRoleid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_user.firstName</code>.
     */
    @Override
    public TbUserRecord setFirstname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.firstName</code>.
     */
    @Override
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_user.lastName</code>.
     */
    @Override
    public TbUserRecord setLastname(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.lastName</code>.
     */
    @Override
    public String getLastname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_user.email</code>.
     */
    @Override
    public TbUserRecord setEmail(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.email</code>.
     */
    @Override
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tb_user.mobile</code>.
     */
    @Override
    public TbUserRecord setMobile(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.mobile</code>.
     */
    @Override
    public String getMobile() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tb_user.hashedPassword</code>.
     */
    @Override
    public TbUserRecord setHashedpassword(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.hashedPassword</code>.
     */
    @Override
    public String getHashedpassword() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tb_user.passwordSalt</code>.
     */
    @Override
    public TbUserRecord setPasswordsalt(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.passwordSalt</code>.
     */
    @Override
    public String getPasswordsalt() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.tb_user.companyCode</code>.
     */
    @Override
    public TbUserRecord setCompanycode(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.companyCode</code>.
     */
    @Override
    public String getCompanycode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.tb_user.createdOn</code>.
     */
    @Override
    public TbUserRecord setCreatedon(OffsetDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.createdOn</code>.
     */
    @Override
    public OffsetDateTime getCreatedon() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.tb_user.createdBy</code>.
     */
    @Override
    public TbUserRecord setCreatedby(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_user.createdBy</code>.
     */
    @Override
    public String getCreatedby() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, String, String, String, String, String, String, OffsetDateTime, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, String, String, String, String, String, String, String, OffsetDateTime, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TbUser.TB_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return TbUser.TB_USER.ROLEID;
    }

    @Override
    public Field<String> field3() {
        return TbUser.TB_USER.FIRSTNAME;
    }

    @Override
    public Field<String> field4() {
        return TbUser.TB_USER.LASTNAME;
    }

    @Override
    public Field<String> field5() {
        return TbUser.TB_USER.EMAIL;
    }

    @Override
    public Field<String> field6() {
        return TbUser.TB_USER.MOBILE;
    }

    @Override
    public Field<String> field7() {
        return TbUser.TB_USER.HASHEDPASSWORD;
    }

    @Override
    public Field<String> field8() {
        return TbUser.TB_USER.PASSWORDSALT;
    }

    @Override
    public Field<String> field9() {
        return TbUser.TB_USER.COMPANYCODE;
    }

    @Override
    public Field<OffsetDateTime> field10() {
        return TbUser.TB_USER.CREATEDON;
    }

    @Override
    public Field<String> field11() {
        return TbUser.TB_USER.CREATEDBY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRoleid();
    }

    @Override
    public String component3() {
        return getFirstname();
    }

    @Override
    public String component4() {
        return getLastname();
    }

    @Override
    public String component5() {
        return getEmail();
    }

    @Override
    public String component6() {
        return getMobile();
    }

    @Override
    public String component7() {
        return getHashedpassword();
    }

    @Override
    public String component8() {
        return getPasswordsalt();
    }

    @Override
    public String component9() {
        return getCompanycode();
    }

    @Override
    public OffsetDateTime component10() {
        return getCreatedon();
    }

    @Override
    public String component11() {
        return getCreatedby();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRoleid();
    }

    @Override
    public String value3() {
        return getFirstname();
    }

    @Override
    public String value4() {
        return getLastname();
    }

    @Override
    public String value5() {
        return getEmail();
    }

    @Override
    public String value6() {
        return getMobile();
    }

    @Override
    public String value7() {
        return getHashedpassword();
    }

    @Override
    public String value8() {
        return getPasswordsalt();
    }

    @Override
    public String value9() {
        return getCompanycode();
    }

    @Override
    public OffsetDateTime value10() {
        return getCreatedon();
    }

    @Override
    public String value11() {
        return getCreatedby();
    }

    @Override
    public TbUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TbUserRecord value2(String value) {
        setRoleid(value);
        return this;
    }

    @Override
    public TbUserRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public TbUserRecord value4(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public TbUserRecord value5(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public TbUserRecord value6(String value) {
        setMobile(value);
        return this;
    }

    @Override
    public TbUserRecord value7(String value) {
        setHashedpassword(value);
        return this;
    }

    @Override
    public TbUserRecord value8(String value) {
        setPasswordsalt(value);
        return this;
    }

    @Override
    public TbUserRecord value9(String value) {
        setCompanycode(value);
        return this;
    }

    @Override
    public TbUserRecord value10(OffsetDateTime value) {
        setCreatedon(value);
        return this;
    }

    @Override
    public TbUserRecord value11(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public TbUserRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, OffsetDateTime value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITbUser from) {
        setId(from.getId());
        setRoleid(from.getRoleid());
        setFirstname(from.getFirstname());
        setLastname(from.getLastname());
        setEmail(from.getEmail());
        setMobile(from.getMobile());
        setHashedpassword(from.getHashedpassword());
        setPasswordsalt(from.getPasswordsalt());
        setCompanycode(from.getCompanycode());
        setCreatedon(from.getCreatedon());
        setCreatedby(from.getCreatedby());
    }

    @Override
    public <E extends ITbUser> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbUserRecord
     */
    public TbUserRecord() {
        super(TbUser.TB_USER);
    }

    /**
     * Create a detached, initialised TbUserRecord
     */
    public TbUserRecord(Long id, String roleid, String firstname, String lastname, String email, String mobile, String hashedpassword, String passwordsalt, String companycode, OffsetDateTime createdon, String createdby) {
        super(TbUser.TB_USER);

        set(0, id);
        set(1, roleid);
        set(2, firstname);
        set(3, lastname);
        set(4, email);
        set(5, mobile);
        set(6, hashedpassword);
        set(7, passwordsalt);
        set(8, companycode);
        set(9, createdon);
        set(10, createdby);
    }

    public TbUserRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
