/*
 * This file is generated by jOOQ.
 */
package jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.OffsetTime;

import javax.annotation.Generated;


/**
 * This table contains user login credentials and assigned user role
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITbUser extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.tb_user.id</code>.
     */
    public ITbUser setId(Long value);

    /**
     * Getter for <code>public.tb_user.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.tb_user.role_id</code>.
     */
    public ITbUser setRoleId(Long value);

    /**
     * Getter for <code>public.tb_user.role_id</code>.
     */
    public Long getRoleId();

    /**
     * Setter for <code>public.tb_user.first_name</code>.
     */
    public ITbUser setFirstName(String value);

    /**
     * Getter for <code>public.tb_user.first_name</code>.
     */
    public String getFirstName();

    /**
     * Setter for <code>public.tb_user.last_name</code>.
     */
    public ITbUser setLastName(String value);

    /**
     * Getter for <code>public.tb_user.last_name</code>.
     */
    public String getLastName();

    /**
     * Setter for <code>public.tb_user.email</code>.
     */
    public ITbUser setEmail(String value);

    /**
     * Getter for <code>public.tb_user.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>public.tb_user.mobile</code>.
     */
    public ITbUser setMobile(String value);

    /**
     * Getter for <code>public.tb_user.mobile</code>.
     */
    public String getMobile();

    /**
     * Setter for <code>public.tb_user.secret</code>.
     */
    public ITbUser setSecret(String value);

    /**
     * Getter for <code>public.tb_user.secret</code>.
     */
    public String getSecret();

    /**
     * Setter for <code>public.tb_user.salt</code>.
     */
    public ITbUser setSalt(String value);

    /**
     * Getter for <code>public.tb_user.salt</code>.
     */
    public String getSalt();

    /**
     * Setter for <code>public.tb_user.company_code</code>.
     */
    public ITbUser setCompanyCode(String value);

    /**
     * Getter for <code>public.tb_user.company_code</code>.
     */
    public String getCompanyCode();

    /**
     * Setter for <code>public.tb_user.created_on</code>.
     */
    public ITbUser setCreatedOn(OffsetTime value);

    /**
     * Getter for <code>public.tb_user.created_on</code>.
     */
    public OffsetTime getCreatedOn();

    /**
     * Setter for <code>public.tb_user.created_by</code>.
     */
    public ITbUser setCreatedBy(String value);

    /**
     * Getter for <code>public.tb_user.created_by</code>.
     */
    public String getCreatedBy();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITbUser
     */
    public void from(ITbUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITbUser
     */
    public <E extends ITbUser> E into(E into);

    @Override
    public default ITbUser fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getLong("id"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.Long",e);
        }
        try {
            setRoleId(json.getLong("role_id"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("role_id","java.lang.Long",e);
        }
        try {
            setFirstName(json.getString("first_name"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("first_name","java.lang.String",e);
        }
        try {
            setLastName(json.getString("last_name"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("last_name","java.lang.String",e);
        }
        try {
            setEmail(json.getString("email"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("email","java.lang.String",e);
        }
        try {
            setMobile(json.getString("mobile"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("mobile","java.lang.String",e);
        }
        try {
            setSecret(json.getString("secret"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("secret","java.lang.String",e);
        }
        try {
            setSalt(json.getString("salt"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("salt","java.lang.String",e);
        }
        try {
            setCompanyCode(json.getString("company_code"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("company_code","java.lang.String",e);
        }
        try {
            // Omitting unrecognized type java.time.OffsetTime for column created_on!
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("created_on","java.time.OffsetTime",e);
        }
        try {
            setCreatedBy(json.getString("created_by"));
        } catch (ClassCastException e) {
            throw new UnexpectedJsonValueType("created_by","java.lang.String",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("role_id",getRoleId());
        json.put("first_name",getFirstName());
        json.put("last_name",getLastName());
        json.put("email",getEmail());
        json.put("mobile",getMobile());
        json.put("secret",getSecret());
        json.put("salt",getSalt());
        json.put("company_code",getCompanyCode());
        // Omitting unrecognized type java.time.OffsetTime for column created_on!
        json.put("created_by",getCreatedBy());
        return json;
    }

}
